spring:
  application:
    name: eurekakConsumer02
server:
  port: 12002


eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka/
